name: flutterbascis
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  equatable:
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  provider:
  go_router: ^6.2.0
  sqflite: any
  path_provider: any
  flutter_pdfview: ^1.2.9
  connectivity_plus: any
  http:
  webview_flutter: ^4.0.7
  url_launcher: ^6.1.10
  external_app_launcher: ^3.1.0
  flutter_launcher_icons: ^0.12.0
  hawk_fab_menu: ^1.2.0
  flutter_speed_dial: ^6.2.0
  animated_splash_screen: ^1.3.0
  shared_preferences: ^2.0.20
  flutter_native_splash: ^2.2.19

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash:
  background_image: "assets/images/splash-screen.png"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/sonali_esheba_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
#  web:
#    generate: true
#    image_path: "path/to/image.png"
#    background_color: "#hexcode"
#    theme_color: "#hexcode"
#  windows:
#    generate: true
#    image_path: "path/to/image.png"
#    icon_size: 48 # min:48, max:256, default: 48
#  macos:
#    generate: true
#    image_path: "path/to/image.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/pdf/
    - i18n/
    - assets/images/