// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcygWvKfTFhYL1QKBcgnU9fGCm505-TFQ',
    appId: '1:973458232316:web:5357cb1501dd83790e1879',
    messagingSenderId: '973458232316',
    projectId: 'fir-test-4ad0b',
    authDomain: 'fir-test-4ad0b.firebaseapp.com',
    storageBucket: 'fir-test-4ad0b.appspot.com',
    measurementId: 'G-YGFR5RC3WN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBip70LVWoT-C--aliZ74tBWtD85oetsh8',
    appId: '1:973458232316:android:a5cb5a74ebe1868f0e1879',
    messagingSenderId: '973458232316',
    projectId: 'fir-test-4ad0b',
    storageBucket: 'fir-test-4ad0b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1JIVP9_kOq-m5mxfV4tY7PPYJB3nfu80',
    appId: '1:973458232316:ios:39ceaf864982263b0e1879',
    messagingSenderId: '973458232316',
    projectId: 'fir-test-4ad0b',
    storageBucket: 'fir-test-4ad0b.appspot.com',
    iosClientId: '973458232316-97pieal5sqnj9uk5r92v45n0j76evd8u.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterbascis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1JIVP9_kOq-m5mxfV4tY7PPYJB3nfu80',
    appId: '1:973458232316:ios:39ceaf864982263b0e1879',
    messagingSenderId: '973458232316',
    projectId: 'fir-test-4ad0b',
    storageBucket: 'fir-test-4ad0b.appspot.com',
    iosClientId: '973458232316-97pieal5sqnj9uk5r92v45n0j76evd8u.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterbascis',
  );
}
